language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
before_script:
  - npm install
  - npm run install-packages
  - npm run build
script:
  - npm run ci
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    target_branch: master
    local_dir: packages/client/build/
    fqdn: streams.codestar.nl
